const images = {
  avatarmixi: require("./avt-mixi.jpg"),
  avatarsofm: require("./avatar-sofm.jpg"),
  avatarnhism: require("./avatar-nhism.jpg"),
  avatarkirin: require("./avatar-kirin.jpg"),
  avatartrucnhan: require("./avatar-trucnhan.jpg"),
  avatardenvau: require("./avatar-denvau.jpg"),
  avatarchillnfree: require("./avatar-chillnfree.jpg"),
  avatarLck: require("./avt-lck.jpg"),
  avatar: require("./avatar.jpg"),
  video1: require("./video1.jpg"),
  video2: require("./video2.jpg"),
  video3: require("./video3.jpg"),
  video4: require("./video4.jpg"),
  shorts1: require("./shorts-1.jpg"),
  shorts2: require("./shorts-2.jpg"),
  shorts3: require("./shorts-3.jpg"),
  shorts4: require("./shorts-4.jpg"),
  shorts5: require("./shorts-5.jpg"),
  shorts6: require("./shorts-6.jpg"),
  shortsPage1: require("./shorts-page1.jpg"),
  channelsShorts1: require("./shorts-channels1.jpg"),
};

export default images;
